- name: playbook to create a new user devop and setting password using ansible_vault
  hosts: all
  become: true
  gather_facts: true
  force_handlers: true

  vars_files:
      - my_vault_user_password.yml

  vars:
    - username: netman
    - groupname: engineer

  tasks:

     - name: check the group already exits
       ansible.builtin.group:
        name: "{{ groupname }}"
        state: present
    
     - name: create a useing {{ username }}
       ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        groups:
         - wheel
         - "{{ groupname }}"
        append: yes
        shell: /bin/bash
        create_home: true
        home: /home/{{ username }}
        comment: "{{ username }} user"
        generate_ssh_key: true